import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { Reveal } from "@/components/Reveal";

export const metadata = {
  title: "Terms of Use | Market Mind Live",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-canvas">
      <Navbar />

      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-12 sm:py-16">
        <Reveal>
          <h1 className="text-xl font-bold uppercase tracking-wider font-mono text-ink">Terms of Use</h1>
          <p className="mt-1 font-mono text-xs uppercase tracking-wide text-ink-faint">Last updated: 2026</p>

          <div className="mt-8 flex flex-col gap-6 text-sm leading-relaxed text-ink-muted">
            <div className="space-y-2">
              <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">No financial advice</h2>
              <p>
                Market Mind Live is provided for educational and informational purposes only. Nothing on this
                platform - including charts, technical indicators, predictions, risk scores, backtests, or AI
                Insights chat responses - constitutes financial, investment, legal, or tax advice.
              </p>
            </div>

            <div className="space-y-2">
              <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">No guaranteed outcomes</h2>
              <p>
                Predictions and risk scores are generated by a rules-based engine from historical and live
                market data. Past performance and backtested results do not guarantee future outcomes. Market
                data may be delayed or unavailable at times.
              </p>
            </div>

            <div className="space-y-2">
              <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">Your responsibility</h2>
              <p>
                You are solely responsible for any trading or investment decisions you make. Always do your own
                research and consult a licensed financial professional before acting on any information
                presented on this platform.
              </p>
            </div>

            <div className="space-y-2">
              <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">Service availability</h2>
              <p>
                The platform is provided &ldquo;as is&rdquo; without warranties of any kind. Features, data sources, and
                availability may change without notice.
              </p>
            </div>

            <p>
              Questions about these terms can be sent via email to{" "}
              <a href="mailto:support@marketmindlive.app" className="text-brand hover:underline font-mono text-2xs uppercase font-bold tracking-wider">
                support@marketmindlive.app
              </a>.
            </p>
          </div>
        </Reveal>
      </main>

      <Footer />
    </div>
  );
}
