
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { Reveal } from "@/components/Reveal";
import { BacktestingSimulation3D } from "@/components/BacktestingSimulation3D";

export const metadata = {
  title: "Terms of Use | Market Mind Live",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-canvas">
      <Navbar />

      <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-12 sm:py-16">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-12 lg:items-start">
          {/* Left Column: Terms content */}
          <div className="lg:col-span-8 space-y-6">
            <Reveal delay={0}>
              <h1 className="text-xl font-bold uppercase tracking-wider font-mono text-ink">Terms of Use</h1>
              <p className="mt-1 font-mono text-xs uppercase tracking-wide text-ink-faint">Last updated: 2026</p>
            </Reveal>

            <div className="mt-8 flex flex-col gap-6 text-sm leading-relaxed text-ink-muted">
              <Reveal delay={0.06} className="space-y-2">
                <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">No financial advice</h2>
                <p>
                  Market Mind Live is provided for educational and informational purposes only. Nothing on this
                  platform - including charts, technical indicators, predictions, risk scores, backtests, or AI
                  Insights chat responses - constitutes financial, investment, legal, or tax advice.
                </p>
              </Reveal>

              <Reveal delay={0.12} className="space-y-2">
                <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">No guaranteed outcomes</h2>
                <p>
                  Predictions and risk scores are generated by a rules-based engine from historical and live
                  market data. Past performance and backtested results do not guarantee future outcomes. Market
                  data may be delayed or unavailable at times.
                </p>
              </Reveal>

              <Reveal delay={0.18} className="space-y-2">
                <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">Your responsibility</h2>
                <p>
                  You are solely responsible for any trading or investment decisions you make. Always do your own
                  research and consult a licensed financial professional before acting on any information
                  presented on this platform.
                </p>
              </Reveal>

              <Reveal delay={0.24} className="space-y-2">
                <h2 className="font-mono text-sm font-bold uppercase tracking-wider text-ink">Service availability</h2>
                <p>
                  The platform is provided &ldquo;as is&rdquo; without warranties of any kind. Features, data sources, and
                  availability may change without notice.
                </p>
              </Reveal>

              <Reveal delay={0.3}>
                <p>
                  Questions about these terms can be sent via email to{" "}
                  <a href="mailto:support@marketmindlive.app" className="text-brand hover:underline font-mono text-[10px] uppercase font-bold tracking-wider">
                    support@marketmindlive.app
                  </a>.
                </p>
              </Reveal>
            </div>
          </div>

          {/* Right Column: 3D visual representing boundaries and simulation testing */}
          <div className="lg:col-span-4 w-full flex items-center justify-center sticky top-24">
            <Reveal delay={0.3}>
              <BacktestingSimulation3D className="mx-auto max-w-[180px] lg:max-w-none opacity-60 hover:opacity-100 transition-opacity duration-300" />
            </Reveal>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
