import Link from "next/link";

import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";

export const metadata = {
  title: "Terms of Use | Market Mind Live",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-canvas">
      <Navbar />

      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-10 sm:py-14">
        <h1 className="text-3xl font-semibold tracking-tight text-ink">Terms of Use</h1>
        <p className="mt-2 text-sm text-ink-faint">Last updated: 2026</p>

        <div className="mt-8 flex flex-col gap-6 text-sm leading-relaxed text-ink-muted">
          <section>
            <h2 className="text-base font-semibold text-ink">No financial advice</h2>
            <p className="mt-2">
              Market Mind Live is provided for educational and informational purposes only. Nothing on this
              platform - including charts, technical indicators, predictions, risk scores, backtests, or AI
              Insights chat responses - constitutes financial, investment, legal, or tax advice.
            </p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink">No guaranteed outcomes</h2>
            <p className="mt-2">
              Predictions and risk scores are generated by a rules-based engine from historical and live
              market data. Past performance and backtested results do not guarantee future outcomes. Market
              data may be delayed or unavailable at times.
            </p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink">Your responsibility</h2>
            <p className="mt-2">
              You are solely responsible for any trading or investment decisions you make. Always do your own
              research and consult a licensed financial professional before acting on any information
              presented on this platform.
            </p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink">Service availability</h2>
            <p className="mt-2">
              The platform is provided "as is" without warranties of any kind. Features, data sources, and
              availability may change without notice.
            </p>
          </section>
          <p>
            Questions about these terms can be sent via the <Link href="/contact" className="text-brand hover:underline">contact page</Link>.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
