"""initial tables

Revision ID: 4ccc1cd4c6c4
Revises: 
Create Date: 2026-07-05 22:18:12.716629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ccc1cd4c6c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatfeedbackrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatfeedbackrecord_session_id'), 'chatfeedbackrecord', ['session_id'], unique=False)
    op.create_table('device',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictionhistoryrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('price_at_prediction', sa.Float(), nullable=False),
    sa.Column('generated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictionhistoryrecord_symbol'), 'predictionhistoryrecord', ['symbol'], unique=False)
    op.create_table('alertrecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('baseline_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triggered_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertrecord_device_id'), 'alertrecord', ['device_id'], unique=False)
    op.create_index(op.f('ix_alertrecord_symbol'), 'alertrecord', ['symbol'], unique=False)
    op.create_table('chatsessionrecord',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_message_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chatsessionrecord_device_id'), 'chatsessionrecord', ['device_id'], unique=False)
    op.create_table('chatmessagerecord',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chatsessionrecord.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chatmessagerecord_session_id'), 'chatmessagerecord', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessagerecord_session_id'), table_name='chatmessagerecord')
    op.drop_table('chatmessagerecord')
    op.drop_index(op.f('ix_chatsessionrecord_device_id'), table_name='chatsessionrecord')
    op.drop_table('chatsessionrecord')
    op.drop_index(op.f('ix_alertrecord_symbol'), table_name='alertrecord')
    op.drop_index(op.f('ix_alertrecord_device_id'), table_name='alertrecord')
    op.drop_table('alertrecord')
    op.drop_index(op.f('ix_predictionhistoryrecord_symbol'), table_name='predictionhistoryrecord')
    op.drop_table('predictionhistoryrecord')
    op.drop_table('device')
    op.drop_index(op.f('ix_chatfeedbackrecord_session_id'), table_name='chatfeedbackrecord')
    op.drop_table('chatfeedbackrecord')
    # ### end Alembic commands ###
